spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
          native:
            search-locations:
              - file:./config-repo/
              - file:./config-repo/{application}/

server:
  port: ${SERVER_PORT:8888}

management:
  endpoints:
    web:
      exposure:
        include: health,info
